# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "~1.7.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/mendsley/gojwk"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.3"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~2.1.1"

[[constraint]]
  name = "stash.kopano.io/kgol/kcc-go"
  version = "~3.0.0"

[[constraint]]
  name = "stash.kopano.io/kgol/rndm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "stash.kopano.io/kgol/oidc-go"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
